services:
  database:
    image: postgres:17
    container_name: beco-rural-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: beco-rural
